# Generated by Django 3.0.2 on 2020-01-22 08:27

import django.db.models.deletion
import feincms.extensions.base
import feincms.module.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "title",
                    models.CharField(
                        help_text="This title is also used for navigation menu items.",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="This is used to build the URL for this page",
                        max_length=150,
                        verbose_name="slug",
                    ),
                ),
                (
                    "in_navigation",
                    models.BooleanField(default=False, verbose_name="in navigation"),
                ),
                (
                    "override_url",
                    models.CharField(
                        blank=True,
                        help_text="Override the target URL. Be sure to include slashes at the beginning and at the end if it is a local URL. This affects both the navigation and subpages' URLs.",
                        max_length=255,
                        verbose_name="override URL",
                    ),
                ),
                (
                    "redirect_to",
                    models.CharField(
                        blank=True,
                        help_text="Target URL for automatic redirects or the primary key of a page.",
                        max_length=255,
                        verbose_name="redirect to",
                    ),
                ),
                (
                    "_cached_url",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        editable=False,
                        max_length=255,
                        verbose_name="Cached URL",
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "template_key",
                    models.CharField(
                        choices=[("base", "Base Template")],
                        default="base",
                        max_length=255,
                        verbose_name="template",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="page.Page",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "page",
                "verbose_name_plural": "pages",
                "ordering": ["tree_id", "lft"],
            },
            bases=(
                models.Model,
                feincms.extensions.base.ExtensionsMixin,
                feincms.module.mixins.ContentModelMixin,
            ),
        ),
        migrations.CreateModel(
            name="OembedContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Insert an URL to an external content you want to embed, e.g. http://www.youtube.com/watch?v=Nd-vBFJN_2E",
                        verbose_name="URL",
                    ),
                ),
                ("region", models.CharField(max_length=255)),
                ("ordering", models.IntegerField(default=0, verbose_name="ordering")),
                (
                    "type",
                    models.CharField(
                        choices=[("default", "Default presentation")],
                        default="default",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oembedcontent_set",
                        to="page.Page",
                    ),
                ),
            ],
            options={
                "verbose_name": "external content",
                "verbose_name_plural": "external contents",
                "db_table": "page_page_oembedcontent",
                "ordering": ["ordering"],
                "permissions": [],
                "abstract": False,
            },
        ),
    ]
